env:
  browser: false
  es6: false
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Net: readonly
  util: readonly
  app: readonly
parserOptions:
  ecmaVersion: 3
rules: {}
